# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Rust test compile and Upload

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable
      - name: Testing
        run: cargo run && cargo run >> $GITHUB_STEP_SUMMARY
  win64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: test
    steps:
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: -r --target x86_64-pc-windows-gnu
  linux64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: test
    steps:
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: -r --target x86_64-unknown-linux-gnu
  linuxARM64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: test
    steps:
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: -r --target armv7-unknown-linux-musleabihf
  SevenZ-Upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [win64, linux64] #, linuxARM64]
    steps:
      - name: 7z Compression
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 build.7z ./target/
      - name: Upload to Gofile # Avoiding File Limits of Github
        run: ./.github/scripts/upload.sh build.7z
        shell: bash
      - name: Clean Workspace
        run: rm -rf ./*
      - name: Delete Branch Cache
        uses: snnaplab/delete-branch-cache-action@v1.0.0
        with:
          github-token: ${{ secrets.TOKEN }}
